#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("YETI.Droid.Resource", IsApplication=true)]

namespace YETI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int ajustes = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int editar = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int flechas = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int gramatica = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int idioma = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int logo = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int logo2 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int oido = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int pausa = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int play = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int prueba = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int refrescar = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int stop = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int vocabulario = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int yeti = 2130771982;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int sliding_tabs = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int toolbar = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Tabbar = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F050000
			public const int audio1 = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
